version: 1.0.{build}
configuration: Release
build:
  project: SplittermondWeaponCalculator.sln
  verbosity: minimal
after_build:
  - ps : cp .\WeaponCalculator\Waffen.csv .\WeaponCalculator\bin\Release\.
artifacts:
- path: WeaponCalculator\bin\Release
  name: WeaponCalculator-%version%
deploy:
- provider: GitHub
  auth_token:
    secure: Pd0tjGABarpRQdEv99s+efMdDRrh5RkK8E1DvhJKOCTY9iBj77aAtZKrRildua08