version: 1.0.{build}
configuration: Release
build:
  project: SplittermondWeaponCalculator.sln
  verbosity: minimal
artifacts:
- path: WeaponCalculator\bin\Release\*
  name: Executable
- path: WeaponCalculator\Waffen.csv
  name: ExampleFile
deploy:
- provider: GitHub
  auth_token:
    secure: Pd0tjGABarpRQdEv99s+efMdDRrh5RkK8E1DvhJKOCTY9iBj77aAtZKrRildua08