version: 1.0.{build}
configuration: Release
build:
  project: SplittermondWeaponCalculator.sln
  verbosity: normal
after_build:
    - ps :.\7z.exe a WeaponCalculator.zip %APPVEYOR_BUILD_FOLDER%\WeaponCalculator\bin\Release\WeaponCalculator.exe %APPVEYOR_BUILD_FOLDER%\WeaponCalculator\Waffen.csv
    - ps : Push-AppveyorArtifact WeaponCalculator.zip
artifacts:
- path: WeaponCalculator.zip
deploy:
- provider: GitHub
  auth_token:
    secure: Pd0tjGABarpRQdEv99s+efMdDRrh5RkK8E1DvhJKOCTY9iBj77aAtZKrRildua08